version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mounts current code into the container
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - PYTHONUNBUFFERED=1
    # Auto-reloads on changes
    command: python manage.py runserver 0.0.0.0:8000